use rustdoc_types::{Attribute, Impl, Item};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ImplKind {
    /// E.g. `impl Foo` or `impl<'a> Foo<'a>`
    Inherent,

    /// E.g. `impl Bar for Foo {}`
    Trait,

    /// Auto-generated by `#[derive(...)]`
    AutoDerived,

    /// Auto-trait impl such as `impl Sync for Foo`
    AutoTrait,

    /// Blanket impls such as `impl<T> Any for T`
    Blanket,
}

impl ImplKind {
    pub fn from(impl_item: &Item, impl_: &Impl) -> Self {
        let has_blanket_impl = impl_.blanket_impl.is_some();
        let is_automatically_derived = impl_item.attrs.contains(&Attribute::AutomaticallyDerived);

        match (impl_.is_synthetic, has_blanket_impl) {
            (true, false) => ImplKind::AutoTrait,
            (false, true) => ImplKind::Blanket,
            _ if is_automatically_derived => ImplKind::AutoDerived,
            _ if impl_.trait_.is_none() => ImplKind::Inherent,
            _ => ImplKind::Trait,
        }
    }
}

impl ImplKind {
    /// Check if this impl should be included (hardcoded to -s -s behavior).
    pub fn is_active(&self) -> bool {
        match self {
            ImplKind::Blanket => false,    // omit_blanket_impls: true
            ImplKind::AutoTrait => false,  // omit_auto_trait_impls: true
            ImplKind::AutoDerived => true, // omit_auto_derived_impls: false
            ImplKind::Inherent | ImplKind::Trait => true,
        }
    }
}
