use std::path::PathBuf;

/// Helper function to get the path to rustdoc JSON for a test crate.
/// The JSON is generated by the nextest setup script (scripts/generate-test-docs.sh)
/// before tests run.
pub fn get_rustdoc_json_path(crate_name: &str) -> PathBuf {
    let workspace_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();

    let target_dir = workspace_root.join("target");

    // The JSON file is in target/doc/{crate_name}.json
    // Note: Rust converts hyphens to underscores in crate names for file names
    let json_filename = crate_name.replace('-', "_");
    let json_path = target_dir
        .join("doc")
        .join(format!("{}.json", json_filename));

    // Verify the file exists (should be generated by setup script)
    if !json_path.exists() {
        panic!(
            "Rustdoc JSON not found at {:?}.\n\
            This file should be generated by the nextest setup script.\n\
            If running with cargo test, run: scripts/generate-test-docs.sh\n\
            If using nextest, ensure .config/nextest.toml is configured correctly.",
            json_path
        );
    }

    json_path
}
